# Generated by Django 4.0.2 on 2022-03-07 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner_document',
            options={'permissions': [('can_accept_primary', 'can accept the primary document?'), ('can_accept_after_primary', 'can accept other document after primaries?')]},
        ),
    ]
