# Generated by Django 4.0.6 on 2022-08-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pass_number',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
