# Generated by Django 4.0.2 on 2022-03-21 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_delete_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_set_permissions', 'can set permissions for other users'), ('can_set_expert', 'can choose expert from users')]},
        ),
    ]
