# Generated by Django 4.0.2 on 2022-03-07 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_owner_document_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_send_request', 'can send request? (documents must be accepted!)')]},
        ),
    ]
