# Generated by Django 4.0.2 on 2022-03-21 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_set_expert', 'can choose expert from users')]},
        ),
    ]
