# Generated by Django 4.0.2 on 2022-03-30 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_user_first_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_login',
        ),
    ]
