# Generated by Django 4.0.2 on 2022-04-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_user_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_num',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
