# Generated by Django 4.0.2 on 2022-04-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_user_student_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_create',
            field=models.BooleanField(default=False),
        ),
    ]
