# Generated by Django 4.0.2 on 2022-04-06 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import educational.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeFieldStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('document', models.JSONField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educational.degreefieldstudy')),
            ],
        ),
        migrations.CreateModel(
            name='EducationalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[(1, 'must be approved by a register expert'), (2, 'must be approved by an educational expert'), (3, 'must be approved by a financial expert'), (4, 'must be re-approved by the educational expert'), (5, 'must be re-approved by the financial expert'), (6, 'educational expert must approved final submit'), (7, 'request is submitted'), (0, 'request is rejected')], default=(1, 'must be approved by a register expert'), max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('average', models.CharField(blank=True, max_length=10, null=True)),
                ('former_field_study', models.CharField(blank=True, max_length=25, null=True)),
                ('former_university', models.CharField(blank=True, max_length=25, null=True)),
                ('final_status', models.BooleanField(default=False)),
                ('reject', models.BooleanField(default=False)),
                ('tracking_code', models.CharField(blank=True, max_length=20, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('total_coast', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('request_expert_educational', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_expert_educational', to=settings.AUTH_USER_MODEL)),
                ('request_expert_financial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_expert_financial', to=settings.AUTH_USER_MODEL)),
                ('request_expert_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_expert_register', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_see_educational_request', 'can see educational request'), ('can_see_financial_request', 'can see financial request'), ('can_see_register_request', 'can see register request')],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_name', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.JSONField(blank=True, null=True)),
                ('document', models.JSONField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='YearSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4)),
                ('status', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educational.yearsemester')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('scholarship', models.BooleanField(default=False)),
                ('expert_price', models.CharField(max_length=25)),
                ('entrance_price', models.CharField(max_length=25)),
                ('degree_field_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.degreefieldstudy')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.universities')),
                ('year_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.yearsemester')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.educationalrequest')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.semester')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.option')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('image', models.ImageField(blank=True, null=True, upload_to=educational.models.owner_image)),
                ('educational_request', models.ManyToManyField(to='educational.EducationalRequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('user_seen', models.BooleanField(blank=True, default=False, null=True)),
                ('user_seen_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('expert_seen', models.BooleanField(blank=True, default=False, null=True)),
                ('expert_seen_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('educational_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educational.educationalrequest')),
                ('message_expert', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='message_expert', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
