# Generated by Django 4.0.2 on 2022-03-02 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeFieldStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('document', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_name', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('document', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='YearSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4)),
                ('status', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educational.yearsemester')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('scholarship', models.BooleanField(default=False)),
                ('expert_price', models.CharField(max_length=25)),
                ('entrance_price', models.CharField(max_length=25)),
                ('degree_field_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.degreefieldstudy')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.universities')),
                ('year_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.yearsemester')),
            ],
        ),
        migrations.CreateModel(
            name='EducationalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.CharField(blank=True, max_length=10, null=True)),
                ('field_study', models.CharField(blank=True, max_length=25, null=True)),
                ('former_university', models.CharField(blank=True, max_length=25, null=True)),
                ('status', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.semester')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.owner_document')),
            ],
        ),
    ]
