# Generated by Django 4.0.2 on 2022-04-07 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedoption',
            name='user',
        ),
        migrations.AddField(
            model_name='selectedoption',
            name='request',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='educational.educationalrequest'),
            preserve_default=False,
        ),
    ]
