# Generated by Django 4.0.2 on 2022-03-08 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerdocument',
            old_name='owner',
            new_name='user',
        ),
    ]
