# Generated by Django 4.0.2 on 2022-03-09 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerdocument',
            name='educational_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='educational.educationalrequest'),
        ),
    ]
