# Generated by Django 4.0.2 on 2022-02-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree_field_study',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
