# Generated by Django 4.0.2 on 2022-03-17 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('educational', '0002_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='massage_expert',
        ),
        migrations.AddField(
            model_name='message',
            name='message_expert',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='message_expert', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
