# Generated by Django 4.0.2 on 2022-04-10 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0002_remove_selectedoption_user_selectedoption_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='educational.educationalrequest')),
            ],
        ),
    ]
