# Generated by Django 4.0.4 on 2022-05-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0002_ownerdocument_eof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerdocument',
            name='eof',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
