# Generated by Django 4.0.2 on 2022-02-23 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('educational', '0002_alter_degree_field_study_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educational_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.CharField(blank=True, max_length=10, null=True)),
                ('field_study', models.CharField(blank=True, max_length=25, null=True)),
                ('former_university', models.CharField(blank=True, max_length=25, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.semester')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.owner_document')),
            ],
        ),
        migrations.DeleteModel(
            name='Educational_history',
        ),
    ]
