# Generated by Django 4.0.2 on 2022-03-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0003_remove_message_massage_expert_message_message_expert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='seen',
        ),
        migrations.AddField(
            model_name='message',
            name='expert_seen_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='user_seen_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
