# Generated by Django 4.0.2 on 2022-02-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0003_educational_request_delete_educational_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree_field_study',
            name='document',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universities',
            name='document',
            field=models.TextField(blank=True, null=True),
        ),
    ]
