# Generated by Django 4.0.2 on 2022-04-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0003_studentcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universities',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universities',
            name='document',
            field=models.TextField(blank=True, null=True),
        ),
    ]
