# Generated by Django 4.0.4 on 2022-06-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0003_alter_ownerdocument_eof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerdocument',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
