# Generated by Django 4.0.2 on 2022-03-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0004_remove_message_seen_message_expert_seen_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalrequest',
            name='step',
            field=models.CharField(choices=[(1, 'باید توسط کارشناس ثبت\u200cنام تائید شود'), (2, 'باید توسط کارشناس مالی تائید شود'), (3, 'باید توسط کارشناس آموزشی تائید شود')], default=(2, 'باید توسط کارشناس مالی تائید شود'), max_length=1),
        ),
    ]
