# Generated by Django 4.0.2 on 2022-03-12 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0004_ownerdocument_image_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerdocument',
            name='image_status',
        ),
    ]
