# Generated by Django 4.0.2 on 2022-04-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0004_alter_universities_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreefieldstudy',
            name='document',
            field=models.TextField(blank=True, null=True),
        ),
    ]
