# Generated by Django 4.0.2 on 2022-02-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0004_degree_field_study_document_universities_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year_semester',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
