# Generated by Django 4.0.4 on 2022-06-01 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0005_alter_ownerdocument_eof'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('accepted_types', models.JSONField(default=dict)),
            ],
        ),
        migrations.AlterField(
            model_name='ownerdocument',
            name='eof',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='ownerdocument',
            name='document_pattern',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='educational.documentpattern'),
            preserve_default=False,
        ),
    ]
