# Generated by Django 4.0.2 on 2022-03-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0005_remove_ownerdocument_image_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalrequest',
            name='title',
            field=models.CharField(default='uni', max_length=50),
            preserve_default=False,
        ),
    ]
