# Generated by Django 4.0.2 on 2022-02-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0005_alter_year_semester_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='educational_request',
            name='sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educational_request',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='semester',
            name='scholarship',
            field=models.BooleanField(default=False),
        ),
    ]
