# Generated by Django 4.0.2 on 2022-03-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0005_educationalrequest_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalrequest',
            name='step',
            field=models.CharField(choices=[(1, 'باید توسط کارشناس ثبت\u200cنام تائید شود'), (2, 'باید توسط کارشناس مالی تائید شود'), (3, 'باید توسط کارشناس آموزشی تائید شود')], default=(1, 'باید توسط کارشناس ثبت\u200cنام تائید شود'), max_length=1),
        ),
    ]
