# Generated by Django 4.0.4 on 2022-06-01 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document_pattern', '0001_initial'),
        ('educational', '0006_documentpattern_alter_ownerdocument_eof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerdocument',
            name='document_pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_pattern.documentpattern'),
        ),
        migrations.DeleteModel(
            name='DocumentPattern',
        ),
    ]
