# Generated by Django 4.0.2 on 2022-03-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0006_educationalrequest_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerdocument',
            name='educational_request',
        ),
        migrations.AddField(
            model_name='ownerdocument',
            name='educational_request',
            field=models.ManyToManyField(to='educational.EducationalRequest'),
        ),
    ]
