# Generated by Django 4.0.4 on 2022-06-03 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document_pattern', '0002_rename_accepted_types_documentpattern_types'),
        ('educational', '0007_alter_ownerdocument_document_pattern_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerdocument',
            name='document_pattern',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='document_pattern.documentpattern'),
        ),
    ]
