# Generated by Django 4.0.2 on 2022-03-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0007_remove_ownerdocument_educational_request_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationalrequest',
            old_name='field_study',
            new_name='former_field_study',
        ),
        migrations.RenameField(
            model_name='educationalrequest',
            old_name='college',
            new_name='selected_semester',
        ),
    ]
