# Generated by Django 4.0.2 on 2022-03-19 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0007_educationalrequest_educational_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationalrequest',
            old_name='status',
            new_name='register_status',
        ),
    ]
