# Generated by Django 4.0.2 on 2022-03-15 12:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0008_rename_field_study_educationalrequest_former_field_study_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationalrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='SelectedSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.educationalrequest')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational.semester')),
            ],
        ),
    ]
