# Generated by Django 4.0.4 on 2022-06-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0008_alter_ownerdocument_document_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerdocument',
            name='eof',
            field=models.IntegerField(default=0),
        ),
    ]
