# Generated by Django 4.0.2 on 2022-03-19 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('educational', '0008_rename_status_educationalrequest_register_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalrequest',
            name='request_expert',
        ),
        migrations.AddField(
            model_name='educationalrequest',
            name='request_expert_educational',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_expert_educational', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='educationalrequest',
            name='request_expert_financial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_expert_financial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='educationalrequest',
            name='request_expert_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_expert_register', to=settings.AUTH_USER_MODEL),
        ),
    ]
