# Generated by Django 4.0.4 on 2022-06-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0009_alter_ownerdocument_eof'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerdocument',
            name='extra',
            field=models.JSONField(default=dict),
        ),
    ]
