# Generated by Django 4.0.2 on 2022-03-15 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0009_educationalrequest_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalrequest',
            name='selected_semester',
        ),
    ]
