# Generated by Django 4.0.2 on 2022-03-21 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0010_alter_ownerdocument_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationalrequest',
            options={'permissions': [('can_accept_educational_request', 'can accept educational request'), ('can_accept_financial_request', 'can accept financial request'), ('can_accept_register_request', 'can accept register request')]},
        ),
    ]
