# Generated by Django 4.0.2 on 2022-03-15 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0010_remove_educationalrequest_selected_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationalrequest',
            old_name='status',
            new_name='paid',
        ),
    ]
