# Generated by Django 4.0.2 on 2022-03-21 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0011_alter_educationalrequest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationalrequest',
            options={'permissions': [('can_see_educational_request', 'can see educational request'), ('can_see_financial_request', 'can see financial request'), ('can_see_register_request', 'can see register request')]},
        ),
    ]
