# Generated by Django 4.0.2 on 2022-03-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0011_rename_status_educationalrequest_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalrequest',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
