# Generated by Django 4.0.2 on 2022-03-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0012_alter_educationalrequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalrequest',
            name='final_status',
            field=models.BooleanField(default=False),
        ),
    ]
