# Generated by Django 4.0.2 on 2022-03-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0012_educationalrequest_tracking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalrequest',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
