# Generated by Django 4.0.2 on 2022-03-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0013_educationalrequest_final_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalrequest',
            name='step',
            field=models.CharField(choices=[(1, 'must be approved by a register expert'), (2, 'must be approved by a financial expert'), (3, 'must be approved by an educational expert'), (4, 'request is submitted!')], default=(1, 'must be approved by a register expert'), max_length=1),
        ),
    ]
