# Generated by Django 4.0.2 on 2022-03-21 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0014_alter_educationalrequest_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='educational_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educational.educationalrequest'),
        ),
    ]
