# Generated by Django 4.0.2 on 2022-03-25 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0015_alter_message_educational_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalrequest',
            name='sent',
        ),
    ]
