# Generated by Django 4.0.2 on 2022-03-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0016_remove_educationalrequest_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalrequest',
            name='reject',
            field=models.BooleanField(default=False),
        ),
    ]
