# Generated by Django 4.0.2 on 2022-03-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0018_option_selectedoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalrequest',
            name='total_coast',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
