# Generated by Django 4.0.2 on 2022-04-02 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0024_alter_educationalrequest_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalrequest',
            name='educational_status',
        ),
        migrations.RemoveField(
            model_name='educationalrequest',
            name='educational_status_2',
        ),
        migrations.RemoveField(
            model_name='educationalrequest',
            name='financial_status',
        ),
        migrations.RemoveField(
            model_name='educationalrequest',
            name='financial_status_2',
        ),
        migrations.RemoveField(
            model_name='educationalrequest',
            name='register_status',
        ),
        migrations.RemoveField(
            model_name='educationalrequest',
            name='title',
        ),
    ]
