from .login import *
from .register import *
from .logout import *
from .dashboard import *
from .profile import *
from .user_document import *
from .apis import *
from .create_new_staff_user import create_new_staff_user
from .make_staff import make_staff
