# Generated by Django 4.0.4 on 2022-06-21 08:58

from django.db import migrations, models
import document_pattern.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('document_type', models.CharField(choices=[(1, 'Textual'), (2, 'Audio'), (3, 'Video')], max_length=20)),
                ('size', models.IntegerField(default=16)),
                ('sample', models.FileField(null=True, upload_to=document_pattern.models.document_pattern_image)),
                ('extra', models.JSONField(default=dict)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
