# Generated by Django 4.0.4 on 2022-06-01 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_pattern', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentpattern',
            old_name='accepted_types',
            new_name='types',
        ),
    ]
