# Generated by Django 4.0.4 on 2022-06-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_pattern', '0002_alter_documentpattern_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpattern',
            name='types',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='documentpattern',
            name='document_type',
            field=models.CharField(choices=[(1, 'Textual'), (2, 'Video')], max_length=20),
        ),
    ]
