# Generated by Django 4.0.4 on 2022-06-04 06:06

from django.db import migrations, models
import document_pattern.models


class Migration(migrations.Migration):

    dependencies = [
        ('document_pattern', '0003_documentpattern_height_documentpattern_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpattern',
            name='image',
            field=models.ImageField(null=True, upload_to=document_pattern.models.document_pattern_image),
        ),
    ]
