# Generated by Django 4.0.4 on 2022-06-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_pattern', '0004_documentpattern_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpattern',
            name='height',
            field=models.IntegerField(default=4500),
        ),
        migrations.AlterField(
            model_name='documentpattern',
            name='width',
            field=models.IntegerField(default=4500),
        ),
    ]
