from .universities import *
from .year_semester import *
from .apis import *
from .degree_field_study import *
from .semesters import *
from .uni_request import *
from .term_status import term_status
from .reports import reports
from .edit_university_terms import edit_university_terms
from .upload_new_doc import upload_new_doc
from .submit_upload import submit_upload
