from .universities import universities
from .year_semester import year_semester
from .apis import *
from .degree_field_study import degree_field_study
from .uni_degrees_show import uni_degrees_show
from .create_degree_section import create_degree_section
from .semesters import semesters
from .new_semester import new_semester
from .submit_semester import submit_semester
from .uni_request import *
from .term_status import term_status
from .reports import reports
from .edit_university_terms import edit_university_terms
from .upload_new_doc import upload_new_doc
from .submit_upload import submit_upload
from .requests import requests
from .request_single_confirm import request_single_confirm
from .request_single_remove import request_single_remove
from .request_single_detail import request_single_detail
from .options import options
from .option_single import *
from .option_edit import option_edit
